### ISSUE TITLE
Windows 10 calibration

### ISSUE THREAD

**Issue by drclong** [n-e-y-s/G27_Pedals_and_Shifter#11]
I am having an iss where windows is using the first 2 axes as a steeringwheel/joystck. The result is that 2 of the pedals are beginning at the middle of their travel. I know I am doing something wrong but have read the instructions carefully.
Kind regards

**Comment by n-e-y-s** [comment]
The given information is not sufficient for me to understand your issue. What exactly have you done, what is your expected behaviour and what is the actual behaviour? Did you perform the calibration procedure as described in the main page?

**Comment by drclong** [comment]
Thankyou for the response, it is much appreciated. I have followed all instructions using a arduino pro micro board and flashed it with ino file using the arduino pro micro board library. I then calibrated as per the instruction which appeared to succeed. Pressing each pedal showed the appropriate colour range although from top to bottom. The expected behaviour was the pedals would produce a signal in ACC beginning at 0% progressively rising to 100% or vice versa. Actual behaviour was unrecorded but not as expected. I reflashed the board with the sparkfun library. Behaviour improved but still not expected. Actual behavior was 2 of the pedals began at 50% and rose to 100% or 50% to 0% when ACC was changed to reverse pedal signal. 1 pedal functioned as expected. I tried calibrating in windows but the first 2 axis are within the steering axis part of the calibration.

I have noted this information on the Sparkfun Github page "Some boards such as the Arduino Pro and Pro Mini come in more than one flavor. For these you must select the correct processor in the 'Tools' menu." Could this be the issue as I didn't see this note previously as it is right at the bottom of the page?

Please mark this thread as solved. 2 issues were present. RTFM as they say.
1. I had flashed the board with the 3v 10 bit version of the sketch
2. Adjustments within the games that I was unaware of resolved other issues.

Sorry to bother you.

**Comment by n-e-y-s** [comment]
Not a bother at all, don't worry. I'm still not sure if I understand - have you been able to resolve your issue yourself, or are there still open issues and you're looking for help? 

Regarding the inverted signals, it is also possible to invert the signals directly in the calibration application.
