### ISSUE TITLE
The pedal data jitters and interferes with each other

### ISSUE THREAD

**Issue by zhuo-run** [n-e-y-s/G27_Pedals_and_Shifter#2]
@n-e-y-s  Hello, author. The problem I have now is this. The pedal data jitters and interferes with each other. For example, when I step on the brake pedal, the clutch pedal will also move. And even if the three pedals are not touched, the pedal data will have a slight continuous jitter.

**Comment by n-e-y-s** [comment]
I do think that the interference must have something to do with your wiring. Maybe it is best to connect one pedal after the other and check each single connection for interferences.

Regarding the continuous jitter - it is likely that your pedals and the pots inside are suffering from dirt. They need a cleaning from time to time (see e.g. here: https://www.youtube.com/watch?v=I96fkD36MKY). Even after cleaning a little jitter with these pots is normal. Usually you can setup dead zones to compensate this. Another option is to use a more aggressive filter on the pedal signals (you can enable that in the calibration gui). 
There are also replacement kits for the pots here: https://www.3drap.it/product/potentiometer-replacement-kit-logitech-pedals/. These might be necessary for highly-worn pedals. I applied that on two of my pedals and it's working reasonably well.

**Comment by zhuo-run** [comment]
Ok. Let me try. Thank you
