### ISSUE TITLE
Combining two pedals into one axis

### ISSUE THREAD

**Issue by Pertan81** [n-e-y-s/G27_Pedals_and_Shifter#3]
Hi. 

First, it works great! So nice to not need the G27 wheel laying on the floor when using the pedals.
But is there a way to combine gas and clutch pedal? For example, Clutch is Z Axis- and Gas is Z Axis+?

I'm using the pedals as rudder in FlightSim 2020 and having gas and clutch on separate axis will not work for "Rudder Axis" in the game.

**Comment by n-e-y-s** [comment]
So you mean that pressing the clutch should give a negative (or lower) value and pressing the gas should give a positive (or higher) value, pressing none will result in zero (or middle) level.

It should be an easy change to add and normalize the signals to rudder = (-clutch) + (+gas). Do you mean something like that as an option?

**Comment by Pertan81** [comment]
> 
> 
> So you mean that pressing the clutch should give a negative (or lower) value and pressing the gas should give a positive (or higher) value, pressing none will result in zero (or middle) level.

That would work great
> 
> It should be an easy change to add and normalize the signals to rudder = (-clutch) + (+gas). Do you mean something like that as an option?

Yeah, as a option either in the code or in the g27calib program.

**Comment by n-e-y-s** [comment]
You can check the new release https://github.com/n-e-y-s/G27_Pedals_and_Shifter/releases/tag/1.1
You can combine clutch and gas, configurable via GUI.

**Comment by Pertan81** [comment]
> 
> 
> You can check the new release https://github.com/n-e-y-s/G27_Pedals_and_Shifter/releases/tag/1.1
> You can combine clutch and gas, configurable via GUI.

Awesome! Thanks, will try it out immediately.
