### ISSUE TITLE
Wiring

### ISSUE THREAD

**Issue by psamtam** [n-e-y-s/G27_Pedals_and_Shifter#5]
Lots of resistors are seen on the breadboard. What are those resistors for? Isn't it just connect the pin directly to the pin?

**Comment by n-e-y-s** [comment]
That's a misleading image from the original author. The connections are 1 to 1 without any resistors needed. See also here:

https://github.com/functionreturnfunction/G27_Pedals_and_Shifter/issues/13
https://github.com/functionreturnfunction/G27_Pedals_and_Shifter/issues/2
